Feat/40 create command user message
sora-grayscale/ft_irc pull request #108
Opened 2024-02-28 10:43 UTC by sora-grayscale

2024-02-28 18:03 UTC, yuki-shimoda-crypto requested changes
```diff
diff --git a/inc/CommandHandler.hpp b/inc/CommandHandler.hpp
index 997a761..095be81 100644
--- a/inc/CommandHandler.hpp
+++ b/inc/CommandHandler.hpp
@@ -6,6 +6,7 @@
 #include "User.hpp"
 #include <string>
 #include <vector>
+#include <sstream>
 
 class CommandHandler {
 public:
@@ -16,15 +17,18 @@ public:
   ~CommandHandler();
 private:
   Server &_server;
+  std::string _prefix;
+  std::string _command;
+  std::vector<std::string> _params;
+
 
   void parseCommand(const std::string &commad);
   void executeCommand(const std::string &commandName,
                       const std::vector<std::string> &params, User &user);
   // command
-  std::string PASS(const std::string &commandName,
-                   const std::vector<std::string> &params, User &user);
-  std::string USER(const std::string &commandName,
-                   const std::vector<std::string> &params, User &user);
+  const std::string PASS(User &user);
+  const std::string USER(User &user);
+
 };
 
 #endif
diff --git a/src/Replies.cpp b/src/Replies.cpp
index 434b31a..e3f1e41 100644
--- a/src/Replies.cpp
+++ b/src/Replies.cpp
@@ -18,3 +18,12 @@ const std::string Replies::ERR_ALREADYREGISTRED() {
   message += ":Unauthorized command (already registered)";
   return (message);
 }
+
+// 464
+const std::string Replies::ERR_PASSWDMISMATCH() {
+  std::string message;
+
+  message += "464 ";
+  message += ":Password incorrect";
+  return (message);
+}


```
[patch.txt](https://github.com/sora-grayscale/ft_irc/files/14438335/patch.txt)

2024-02-29 02:03 UTC, sora-grayscale commented on src/CommandHandler.cpp
> +  }
[2.3.1 拡張 BNF によるメッセージフォーマット](https://solareenlo.com/rfc2812/the-irc-client-specification/message-format-in-augumented-bnf.html#231-%E6%8B%A1%E5%BC%B5-bnf-%E3%81%AB%E3%82%88%E3%82%8B%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8%E3%83%95%E3%82%A9%E3%83%BC%E3%83%9E%E3%83%83%E3%83%88)
user = 1*( %x01-09 / %x0B-0C / %x0E-1F / %x21-3F / %x41-FF )
; any octet except NUL, CR, LF, " " and "@"

2024-02-29 02:09 UTC, sora-grayscale commented on src/CommandHandler.cpp
>  }
> v3に合わせてreturn Replies::ERR_PASSWDMISMATCH();を送りましょう
V3に合わせるなら一番最初のCAPからなにからすべてV3に合わせることになりそうだけどその方向性？

> PASSコマンドは何度も送れるのでuser.getState() != User::NONE && user.getState() != User::PASSのほうが良いかもしれないです。
MATCHしたらそのあとはもう見ないから実質NONEがtrueの時だけPASSコマンドを実行するという理解だった．

2024-02-29 03:48 UTC, yuki-shimoda-crypto commented
[patch.txt](https://github.com/sora-grayscale/ft_irc/files/14442560/patch.txt)
パッチ送っておいた

2024-02-29 06:03 UTC, yuki-shimoda-crypto approved these changes

2024-02-29 06:03 UTC, merged