65 create command connect message
sora-grayscale/ft_irc pull request #132
Opened 2024-03-09 03:46 UTC by sora-grayscale

2024-03-09 03:47 UTC, sora-grayscale commented
TIMEをmergeしています
先TIMEコマンドを見ていただけると神

2024-03-11 04:37 UTC, yuki-shimoda-crypto requested changes

2024-03-11 04:37 UTC, yuki-shimoda-crypto commented on src/CommandHandler.cpp
> +  if (this->_params.at(0).empty()) {
```suggestion
  if (this->_params.size() < 2) {
```
```
> [3.4.7](https://www.rfc-editor.org/rfc/rfc2812#section-3.4.7) Connect message
> 
>       Command: CONNECT
>     Parameters: <target server> <port> [ <remote server> ]
```

2024-03-11 04:37 UTC, yuki-shimoda-crypto commented on src/CommandHandler.cpp
>    std::time_t result = std::time(nullptr);
```suggestion
  std::time_t result = std::time(NULL);
```

2024-03-11 04:37 UTC, yuki-shimoda-crypto commented on inc/CommandHandler.hpp
+#include <ctime>

2024-03-11 08:36 UTC, merged