Feat/47 create command join message
sora-grayscale/ft_irc pull request #137
Opened 2024-03-09 09:32 UTC by yuki-shimoda-crypto

2024-03-11 09:29 UTC, yuki-shimoda-crypto commented
merge ok

2024-03-11 10:50 UTC, sora-grayscale reviewed
JOIN #hello
で403 #hello :No such channelが帰ってきてしまう

2024-03-11 10:50 UTC, sora-grayscale commented on src/Replies.cpp
> +  message += "\r\n";
```suggestion
//  message += "\r\n";
```

2024-03-11 10:50 UTC, sora-grayscale commented on src/User.cpp
> +    : _fd(fd), _joinedChannelCount(0), _state(User::NONE) {}
```suggestion
    : _fd(fd), _joinedChannelCount(0), _state(User::NONE) , _modeFlags(User::None){}
```

2024-03-11 10:51 UTC, sora-grayscale requested changes
JOIN #hello
の挙動

2024-03-13 04:51 UTC, sora-grayscale requested changes

2024-03-13 04:51 UTC, sora-grayscale commented on src/Channel.cpp
> +  user.decrementJoinedChannelCount();
```suggestion
  if (this->_users.find(&user) == this->_users.end()) {
    return ;
  }
  this->_users.erase(&user);
  this->_userStatus.erase(&user);
  user.decrementJoinedChannelCount();
```

2024-03-13 04:51 UTC, sora-grayscale commented on src/Channel.cpp
> +  }
```suggestion
  if ((this->_channelModeFlag & flag) == 1) {
    return (true);
  }
  return (false);
```

2024-03-13 04:51 UTC, sora-grayscale commented on src/Channel.cpp
> +  }
return してるなら else式ない方が良いかも

2024-03-13 04:51 UTC, sora-grayscale commented on src/Channel.cpp
> +  }
```suggestion
  }
  return (false);
```

2024-03-13 04:51 UTC, sora-grayscale commented on src/Channel.cpp
> +  }
```suggestion
  }
  return (false);
```

2024-03-13 04:51 UTC, sora-grayscale commented on src/Channel.cpp
> +  }
```suggestion
  }
  return (false);
```

2024-03-13 04:52 UTC, sora-grayscale commented on src/Channel.cpp
> +  user.decrementJoinedChannelCount();
一応のバリデーション

2024-03-13 04:57 UTC, yuki-shimoda-crypto reviewed
change

2024-03-13 05:02 UTC, sora-grayscale approved these changes

2024-03-13 05:02 UTC, merged