[debug]: only enter probrem fix
sora-grayscale/ft_irc pull request #179
Opened 2024-03-20 08:30 UTC by sora-grayscale

noticeの最終だとenterのみの入力で壊れるのでそれのfix

2024-03-21 04:28 UTC, sora-grayscale commented
private messageのbroadcastの方が違ったのも編集済み

2024-03-21 13:09 UTC, yuki-shimoda-crypto requested changes
please merge my branch

2024-03-22 06:12 UTC, sora-grayscale commented
> please merge my branch

DONEです

2024-03-22 06:39 UTC, yuki-shimoda-crypto approved these changes

2024-03-22 06:40 UTC, merged